[phases.setup]
aptPkgs = ["nodejs", "npm", "curl"]
cmds = [
  "npm install -g npm@latest"
]

[phases.build]
cmds = [
  "npm install --prefix server",
  "npm install --prefix client",
  "npm run build --prefix client"
]

[start]
cmd = "node server/src/index.js"
